---
  - name: add group {{ tomcatUser }}
    group: name="{{ tomcatUser }}"

  - name: Create user {{ tomcatUser }} and add to {{ tomcatUser }}
    user: name="{{ tomcatUser }}" group="{{ tomcatUser }}"
    become: True

  - name: delete home dir for symlink of tomcat
    shell: "rm -fr {{ tomcatCatalinaBase }}"
    become: True

  - name: Download Tomcat
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.56/bin/apache-tomcat-7.0.56.tar.gz dest=/opt/apache-tomcat-7.0.56.tar.gz

  - name: Extract archive
    command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.56.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.56

  - name: Symlink install directory
    file: src=/opt/apache-tomcat-7.0.56 path="{{ tomcatCatalinaBase }}" state=link

  - name: Change ownership and rights of Tomcat installation
    file: path="{{ tomcatCatalinaBase }}{{ item.path }}" owner="{{ tomcatUser }}" group="{{ tomcatUser }}" state=directory mode="{{ item.mode }}" recurse=yes
    with_items:
      - { path: '/', mode: 770 }
      - { path: '/logs', mode: 775 }
    become: True

  - name: Configure Tomcat server
    template: src=server.xml dest="{{ tomcatCatalinaBase }}/conf/"
    notify: restart tomcat

  - name: Configure Tomcat users
    template: src=tomcat-users.xml dest="{{ tomcatCatalinaBase }}/conf/"
    notify: restart tomcat

  - name: Install Tomcat init script
    template: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

  - name: Delete Tomcat ROOT webapp folder
    file: path="{{ tomcatCatalinaBase }}/webapps/ROOT" state=absent

  - name: Link application to Tomcat webapps
    file: src="{{ homeDir }}/projectroot" dest="{{ tomcatCatalinaBase }}/webapps/ROOT" state=link force=yes
    when: homeDir is defined and not skipApplicationLink

  - name: Set tomcat service according to {{ tomcatUseService }}
    service: name=tomcat enabled="{{ tomcatUseService | ternary('yes','no')}}"