---
# steamengine/handlers/main.yml

  - name: stop tomcat
    service: name=tomcat state=stopped

  - name: start tomcat
    service: name=tomcat state=started
    when: jbossUseService

  - name: restart tomcat 
    service: name=tomcat state=restarted
    when: jbossUseService
